module.exports = [
	{
		inputs: [
			{ internalType: 'bool', name: '_queueActive', type: 'bool' },
			{
				internalType: 'contract IERC20',
				name: '_nativeAsset',
				type: 'address',
			},
		],
		stateMutability: 'nonpayable',
		type: 'constructor',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'owner',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'approved',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'uint256',
				name: 'tokenId',
				type: 'uint256',
			},
		],
		name: 'Approval',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'owner',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'operator',
				type: 'address',
			},
			{ indexed: false, internalType: 'bool', name: 'approved', type: 'bool' },
		],
		name: 'ApprovalForAll',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'sender',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount0',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount1',
				type: 'uint256',
			},
			{ indexed: true, internalType: 'address', name: 'to', type: 'address' },
		],
		name: 'Burn',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'sender',
				type: 'address',
			},
			{ indexed: true, internalType: 'address', name: 'to', type: 'address' },
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount0',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount1',
				type: 'uint256',
			},
		],
		name: 'Mint',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'previousOwner',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'newOwner',
				type: 'address',
			},
		],
		name: 'OwnershipTransferred',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: true,
				internalType: 'address',
				name: 'sender',
				type: 'address',
			},
			{ indexed: false, internalType: 'uint256', name: 'id', type: 'uint256' },
			{
				indexed: false,
				internalType: 'uint256',
				name: 'liquidity',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'loss',
				type: 'uint256',
			},
		],
		name: 'PositionClosed',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'from', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'to', type: 'address' },
			{ indexed: false, internalType: 'uint256', name: 'id', type: 'uint256' },
			{
				indexed: false,
				internalType: 'uint256',
				name: 'liquidity',
				type: 'uint256',
			},
		],
		name: 'PositionOpened',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: false, internalType: 'bool', name: 'activated', type: 'bool' },
		],
		name: 'QueueActive',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
			{
				indexed: true,
				internalType: 'address',
				name: 'sender',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount0In',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount1In',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount0Out',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'amount1Out',
				type: 'uint256',
			},
			{ indexed: true, internalType: 'address', name: 'to', type: 'address' },
		],
		name: 'Swap',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{
				indexed: false,
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'reserve0',
				type: 'uint256',
			},
			{
				indexed: false,
				internalType: 'uint256',
				name: 'reserve1',
				type: 'uint256',
			},
		],
		name: 'Sync',
		type: 'event',
	},
	{
		anonymous: false,
		inputs: [
			{ indexed: true, internalType: 'address', name: 'from', type: 'address' },
			{ indexed: true, internalType: 'address', name: 'to', type: 'address' },
			{
				indexed: true,
				internalType: 'uint256',
				name: 'tokenId',
				type: 'uint256',
			},
		],
		name: 'Transfer',
		type: 'event',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'to', type: 'address' },
			{ internalType: 'uint256', name: 'tokenId', type: 'uint256' },
		],
		name: 'approve',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'owner', type: 'address' }],
		name: 'balanceOf',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'uint256', name: 'id', type: 'uint256' },
			{ internalType: 'address', name: 'to', type: 'address' },
		],
		name: 'burn',
		outputs: [
			{ internalType: 'uint256', name: 'amountNative', type: 'uint256' },
			{ internalType: 'uint256', name: 'amountForeign', type: 'uint256' },
			{ internalType: 'uint256', name: 'coveredLoss', type: 'uint256' },
		],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
			{ internalType: 'address', name: 'to', type: 'address' },
		],
		name: 'burnFungible',
		outputs: [
			{ internalType: 'uint256', name: 'amountNative', type: 'uint256' },
			{ internalType: 'uint256', name: 'amountForeign', type: 'uint256' },
		],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'synthAmount', type: 'uint256' },
			{ internalType: 'address', name: 'to', type: 'address' },
		],
		name: 'burnSynth',
		outputs: [
			{ internalType: 'uint256', name: 'amountNative', type: 'uint256' },
		],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAssetA',
				type: 'address',
			},
			{
				internalType: 'contract IERC20',
				name: 'foreignAssetB',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'foreignAmountIn', type: 'uint256' },
			{ internalType: 'address', name: 'to', type: 'address' },
		],
		name: 'doubleSwap',
		outputs: [
			{ internalType: 'uint256', name: 'foreignAmountOut', type: 'uint256' },
		],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
		name: 'getApproved',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
		],
		name: 'getReserves',
		outputs: [
			{ internalType: 'uint112', name: 'reserveNative', type: 'uint112' },
			{ internalType: 'uint112', name: 'reserveForeign', type: 'uint112' },
			{ internalType: 'uint32', name: 'blockTimestampLast', type: 'uint32' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract ILPWrapper',
				name: '_wrapper',
				type: 'address',
			},
			{
				internalType: 'contract ISynthFactory',
				name: '_synthFactory',
				type: 'address',
			},
		],
		name: 'initialize',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'owner', type: 'address' },
			{ internalType: 'address', name: 'operator', type: 'address' },
		],
		name: 'isApprovedForAll',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'nativeDeposit', type: 'uint256' },
			{ internalType: 'uint256', name: 'foreignDeposit', type: 'uint256' },
			{ internalType: 'address', name: 'from', type: 'address' },
			{ internalType: 'address', name: 'to', type: 'address' },
		],
		name: 'mint',
		outputs: [{ internalType: 'uint256', name: 'liquidity', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'nativeDeposit', type: 'uint256' },
			{ internalType: 'uint256', name: 'foreignDeposit', type: 'uint256' },
			{ internalType: 'address', name: 'from', type: 'address' },
			{ internalType: 'address', name: 'to', type: 'address' },
		],
		name: 'mintFungible',
		outputs: [{ internalType: 'uint256', name: 'liquidity', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'nativeDeposit', type: 'uint256' },
			{ internalType: 'address', name: 'from', type: 'address' },
			{ internalType: 'address', name: 'to', type: 'address' },
		],
		name: 'mintSynth',
		outputs: [
			{ internalType: 'uint256', name: 'amountSynth', type: 'uint256' },
		],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'name',
		outputs: [{ internalType: 'string', name: '', type: 'string' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'nativeAsset',
		outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'owner',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
		name: 'ownerOf',
		outputs: [{ internalType: 'address', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
		name: 'pairInfo',
		outputs: [
			{ internalType: 'uint256', name: 'totalSupply', type: 'uint256' },
			{ internalType: 'uint112', name: 'reserveNative', type: 'uint112' },
			{ internalType: 'uint112', name: 'reserveForeign', type: 'uint112' },
			{ internalType: 'uint32', name: 'blockTimestampLast', type: 'uint32' },
			{
				components: [
					{ internalType: 'uint256', name: 'nativeLast', type: 'uint256' },
					{ internalType: 'uint256', name: 'foreignLast', type: 'uint256' },
				],
				internalType: 'struct IBasePoolV2.PriceCumulative',
				name: 'priceCumulative',
				type: 'tuple',
			},
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
		],
		name: 'pairSupply',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'id', type: 'uint256' }],
		name: 'positionForeignAsset',
		outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'positionId',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		name: 'positions',
		outputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'creation', type: 'uint256' },
			{ internalType: 'uint256', name: 'liquidity', type: 'uint256' },
			{ internalType: 'uint256', name: 'originalNative', type: 'uint256' },
			{ internalType: 'uint256', name: 'originalForeign', type: 'uint256' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'queueActive',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'renounceOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
		],
		name: 'rescue',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'from', type: 'address' },
			{ internalType: 'address', name: 'to', type: 'address' },
			{ internalType: 'uint256', name: 'tokenId', type: 'uint256' },
		],
		name: 'safeTransferFrom',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'from', type: 'address' },
			{ internalType: 'address', name: 'to', type: 'address' },
			{ internalType: 'uint256', name: 'tokenId', type: 'uint256' },
			{ internalType: 'bytes', name: '_data', type: 'bytes' },
		],
		name: 'safeTransferFrom',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'operator', type: 'address' },
			{ internalType: 'bool', name: 'approved', type: 'bool' },
		],
		name: 'setApprovalForAll',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
		],
		name: 'setFungibleTokenSupport',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
			{ internalType: 'bool', name: 'support', type: 'bool' },
		],
		name: 'setTokenSupport',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
		name: 'supported',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'bytes4', name: 'interfaceId', type: 'bytes4' }],
		name: 'supportsInterface',
		outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{
				internalType: 'contract IERC20',
				name: 'foreignAsset',
				type: 'address',
			},
			{ internalType: 'uint256', name: 'nativeAmountIn', type: 'uint256' },
			{ internalType: 'uint256', name: 'foreignAmountIn', type: 'uint256' },
			{ internalType: 'address', name: 'to', type: 'address' },
		],
		name: 'swap',
		outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'symbol',
		outputs: [{ internalType: 'string', name: '', type: 'string' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'synthFactory',
		outputs: [
			{ internalType: 'contract ISynthFactory', name: '', type: 'address' },
		],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [],
		name: 'toggleQueue',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
		name: 'tokenURI',
		outputs: [{ internalType: 'string', name: '', type: 'string' }],
		stateMutability: 'view',
		type: 'function',
	},
	{
		inputs: [
			{ internalType: 'address', name: 'from', type: 'address' },
			{ internalType: 'address', name: 'to', type: 'address' },
			{ internalType: 'uint256', name: 'tokenId', type: 'uint256' },
		],
		name: 'transferFrom',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
		name: 'transferOwnership',
		outputs: [],
		stateMutability: 'nonpayable',
		type: 'function',
	},
	{
		inputs: [],
		name: 'wrapper',
		outputs: [
			{ internalType: 'contract ILPWrapper', name: '', type: 'address' },
		],
		stateMutability: 'view',
		type: 'function',
	},
]
